[build]
functions = "functions"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"